/* eslint-disable */

/* prettier-ignore */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PurchaseImport } from './routes/purchase'
import { Route as IndexImport } from './routes/index'
import { Route as PurchaseIndexImport } from './routes/purchase/index'
import { Route as PurchaseSignInImport } from './routes/purchase/sign-in'
import { Route as PurchaseLogInImport } from './routes/purchase/log-in'
import { Route as PurchaseCardSelectImport } from './routes/purchase/card-select'

// Create/Update Routes

const PurchaseRoute = PurchaseImport.update({
  path: '/purchase',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PurchaseIndexRoute = PurchaseIndexImport.update({
  path: '/',
  getParentRoute: () => PurchaseRoute,
} as any)

const PurchaseSignInRoute = PurchaseSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => PurchaseRoute,
} as any)

const PurchaseLogInRoute = PurchaseLogInImport.update({
  path: '/log-in',
  getParentRoute: () => PurchaseRoute,
} as any)

const PurchaseCardSelectRoute = PurchaseCardSelectImport.update({
  path: '/card-select',
  getParentRoute: () => PurchaseRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/purchase': {
      preLoaderRoute: typeof PurchaseImport
      parentRoute: typeof rootRoute
    }
    '/purchase/card-select': {
      preLoaderRoute: typeof PurchaseCardSelectImport
      parentRoute: typeof PurchaseImport
    }
    '/purchase/log-in': {
      preLoaderRoute: typeof PurchaseLogInImport
      parentRoute: typeof PurchaseImport
    }
    '/purchase/sign-in': {
      preLoaderRoute: typeof PurchaseSignInImport
      parentRoute: typeof PurchaseImport
    }
    '/purchase/': {
      preLoaderRoute: typeof PurchaseIndexImport
      parentRoute: typeof PurchaseImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PurchaseRoute.addChildren([
    PurchaseCardSelectRoute,
    PurchaseLogInRoute,
    PurchaseSignInRoute,
    PurchaseIndexRoute,
  ]),
])
